import normalFace1 from "../../assets/faceExpression/normal/Blank.svg"
import normalFace2 from "../../assets/faceExpression/normal/Calm.svg"
import normalFace3 from "../../assets/faceExpression/normal/Cheeky.svg"
import normalFace4 from "../../assets/faceExpression/normal/Concerned.svg"
import normalFace5 from "../../assets/faceExpression/normal/AngrywithFang.svg"
import normalFace6 from "../../assets/faceExpression/normal/ConcernedFear.svg"
import normalFace7 from "../../assets/faceExpression/normal/Contempt.svg"
import normalFace8 from "../../assets/faceExpression/normal/Cute.svg"   
import normalFace9 from "../../assets/faceExpression/normal/Driven.svg"   
import normalFace10 from "../../assets/faceExpression/normal/EatingHappy.svg"   
import normalFace11 from "../../assets/faceExpression/normal/Explaining.svg"   
import normalFace12 from "../../assets/faceExpression/normal/EyesClosed.svg"   
import normalFace13 from "../../assets/faceExpression/normal/Old.svg"   
import normalFace14 from "../../assets/faceExpression/normal/Rage.svg"   
import normalFace15 from "../../assets/faceExpression/normal/Serious.svg"
import normalFace16 from "../../assets/faceExpression/normal/Smile.svg"
import normalFace17 from "../../assets/faceExpression/normal/SmileBig.svg"
import normalFace18 from "../../assets/faceExpression/normal/SmileLOL.svg"
import normalFace19 from "../../assets/faceExpression/normal/SmileTeethGap.svg"
import normalFace20 from "../../assets/faceExpression/normal/Solemn.svg"
import normalFace21 from "../../assets/faceExpression/normal/Suspicious.svg"
import normalFace22 from "../../assets/faceExpression/normal/Tired.svg"
import normalFace23 from "../../assets/faceExpression/normal/VeryAngry.svg"

const normalFaceOptions = [normalFace1, normalFace2, normalFace3, normalFace4, normalFace5, normalFace6, normalFace7, normalFace8, normalFace9, normalFace10, normalFace11, normalFace12, normalFace13, normalFace14, normalFace15, normalFace16, normalFace17, normalFace18, normalFace19, normalFace20, normalFace21, normalFace22, normalFace23];

export default normalFaceOptions;